language: csharp
mono: 5.2.0
dotnet: 2.1.300
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      - libunwind8-dev

before_install:
  - nvm install 10.12.0
  - nvm use 10.12.0

script:
  - npm i && npm run build
